### PR TITLE
multiple fixes

### LINKED ISSUE #8: workbench can be dug with material inside
Players can dig their workbench with material left inside, causing the material to be lost when dug.

Please make it that the workbench cannot be dug when items are anywhere inside.

For my reference 1658

### PR DESCRIPTION
**Pull request by fluxionary**
this is a redo of #9 without refactoring. 

* use node timers instead of ABM
* turn recipe into a schema and refund recipe items
* prevent digging when actual items are inside (fixes #8)
* add protection (though not ownership)
* don't lose recipe replacements if there's no room for them
* remove some cruft files (see discussion in #9)

### CODE REVIEW

**Comment by SmallJoker** [comment]
FWIW: I am not sure whether this additional `futil` dependency is desired, hence neglecting the review of this PR. Is it something that server owners would be fine with?

From the mod README:
> WARNING: i am contemplating breaking up the api into multiple namespaces, anticipate changes

Is the inventory API is stable and reliable enough for use?

**Comment by fluxionary** [comment]
> From the mod README:
> 
> > WARNING: i am contemplating breaking up the api into multiple namespaces, anticipate changes
> 
> Is the inventory API is stable and reliable enough for use?

good point! the API has been stable for a while, i'll remove that caveat.

**Comment by fluxionary** [comment]
> FWIW: I am not sure whether this additional futil dependency is desired, hence neglecting the review of this PR. Is it something that server owners would be fine with?

i've switched the license from AGPL to LGPL recently because of the concerns of a server owner (i lost that argument), so objections to the AGPL should be moot. if there's still issues w/ the dependency, i'm fine w/ adding the relevant code directly to this mod's repo, though that will necessitate fixing the code in multiple places if there's a bug, and i just fixed a bug in the `FakeInventory` today.

**Comment by fluxionary** [comment]
i'm going to close this in favor of doing individual PRs for specific issues. i'm starting to appreciate how hard it is to review massive changes. it might be a few months or a year until i get back to this though, i've got a lot on my plate.

**Pull request closed without merging**
